name: todo_app
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  flutter_svg: ^2.0.14
  bounce: ^1.0.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    remove_alpha_ios: true
    image_path: "assets/icons/splash_logo.png"
    min_sdk_android: 24 # android min sdk min:16, default 21
    adaptive_icon_background: "#ffffff" # You can use a color or image for the background
    adaptive_icon_foreground: "assets/icons/splash_logo.png" # For adaptive icons on Android

flutter:
  uses-material-design: true

  assets:
    - assets/images/      
    - assets/icons/ 

  
  
